"""Add a human-readable reference number to incidents.

Part of: backend / migrations.

Why this exists: an incident is identified by a UUID, which nobody can read at a
glance or say to a colleague. This adds a second handle — INC-0001, INC-0002 —
generated by the database so it is unique and safe under concurrent inserts.

The UUID stays the identifier: every foreign key, URL and API call still uses
it. The reference is a label with a unique constraint, and it is searchable.

Written by hand rather than autogenerated: Alembic does not manage sequences,
and the existing rows need backfilling in a defined order before the column can
become NOT NULL.

Revision ID: 8f3c21a4d5e7
Revises: 2607896d33fb
"""

from alembic import op
import sqlalchemy as sa


revision = "8f3c21a4d5e7"
down_revision = "2607896d33fb"
branch_labels = None
depends_on = None

# Four digits keeps INC-0001 aligned with INC-9999 in a list. lpad does not
# truncate, so the ten-thousandth incident simply becomes INC-10000.
REFERENCE_SQL = "'INC-' || lpad(nextval('incident_reference_seq')::text, 4, '0')"


def upgrade() -> None:
    op.execute("CREATE SEQUENCE incident_reference_seq START 1")

    # Nullable first: existing rows have no value yet, and a NOT NULL column
    # with a default would give every one of them a number in whatever order
    # the table happens to be stored in.
    op.add_column("incidents", sa.Column("reference", sa.Text(), nullable=True))

    # Backfill oldest first, so the numbers run in the order things were
    # reported — INC-0001 is genuinely the first incident.
    #
    # row_number() rather than nextval() here: UPDATE ... FROM gives no ordering
    # guarantee, so the sequence would be consumed in whatever order PostgreSQL
    # happens to scan the table and the numbers would come out shuffled. The
    # window function computes each row's position before any row is written.
    op.execute(
        """
        UPDATE incidents AS target
        SET reference = 'INC-' || lpad(ordered.position::text, 4, '0')
        FROM (
            SELECT id, row_number() OVER (ORDER BY created_at, id) AS position
            FROM incidents
        ) AS ordered
        WHERE target.id = ordered.id
        """
    )

    # The backfill bypassed the sequence, so move it past the numbers just used
    # or the next insert would collide with INC-0001.
    op.execute(
        "SELECT setval('incident_reference_seq', GREATEST((SELECT count(*) FROM incidents), 1))"
    )

    op.alter_column("incidents", "reference", nullable=False)
    op.execute(f"ALTER TABLE incidents ALTER COLUMN reference SET DEFAULT {REFERENCE_SQL}")

    # Unique because it is quoted in conversation and typed into the search box:
    # two incidents sharing a number would make both ambiguous. The index also
    # makes an exact-reference lookup fast.
    op.create_index("uq_incidents_reference", "incidents", ["reference"], unique=True)


def downgrade() -> None:
    op.drop_index("uq_incidents_reference", table_name="incidents")
    op.drop_column("incidents", "reference")
    # The sequence is owned by nothing once the column is gone, so it has to be
    # dropped explicitly or a later upgrade fails with "already exists".
    op.execute("DROP SEQUENCE IF EXISTS incident_reference_seq")
