"""create facility incident schema

Creates the 8 tables, 6 native enum types, and every index behind the ACME
facility incident platform. Autogenerated from models.py, then adjusted by hand
in two places — both marked inline below:

  1. downgrade() drops the enum types. Alembic drops the tables that use them
     but never the types themselves, so without this a downgrade followed by an
     upgrade fails with "type user_role already exists".
  2. No CREATE EXTENSION pgcrypto, despite gen_random_uuid() defaults. That
     function moved into core PostgreSQL in 13; local is 18 and the scaffold's
     Aurora cluster is 17.7 (infra/rds.tf), so requiring the extension would
     only add a privilege the migration does not need.

Revision ID: 2607896d33fb
Revises:
Create Date: 2026-09-22 13:54:56.202113
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2607896d33fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native enum types created implicitly by the CREATE TABLE statements below.
# Listed explicitly because only downgrade() has to name them.
ENUM_TYPE_NAMES = (
    "user_role",
    "availability_status",
    "incident_status",
    "incident_priority",
    "incident_category",
    "assignment_request_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('employee', 'facility_admin', 'engineer', name='user_role'), server_default='employee', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # Single %, not %%: autogenerate renders a literal percent doubled, which
    # lands in the stored constraint as a redundant duplicate inside the
    # character class. Harmless to matching, but it misrepresents the rule.
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%+-]+@acme\\.inc$'", name=op.f('ck_users_email_domain')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('engineer_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'busy', 'off', name='availability_status'), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_engineer_profiles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engineer_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_engineer_profiles_user_id'))
    )
    op.create_index('idx_engineer_profiles_availability', 'engineer_profiles', ['availability'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_floors_building_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floors')),
    sa.UniqueConstraint('building_id', 'name', name='uq_floors_building_id_name')
    )
    op.create_index('idx_floors_building_id', 'floors', ['building_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_seats_floor_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('floor_id', 'label', name='uq_seats_floor_id_label')
    )
    op.create_index('idx_seats_floor_id', 'seats', ['floor_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('hvac', 'electrical', 'plumbing', 'furniture', 'network', 'hardware', 'software', 'access_security', 'other', name='incident_category'), server_default='other', nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'blocked', 'resolved', 'closed', name='incident_status'), server_default='open', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='incident_priority'), server_default='medium', nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('seat_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('escalation_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('escalated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['engineer_profiles.id'], name=op.f('fk_incidents_assignee_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk_incidents_building_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name=op.f('fk_incidents_floor_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_incidents_reporter_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_incidents_seat_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index('idx_incidents_assignee_id', 'incidents', ['assignee_id'], unique=False)
    op.create_index('idx_incidents_building_id', 'incidents', ['building_id'], unique=False)
    op.create_index('idx_incidents_category', 'incidents', ['category'], unique=False)
    op.create_index('idx_incidents_floor_id', 'incidents', ['floor_id'], unique=False)
    op.create_index('idx_incidents_priority', 'incidents', ['priority'], unique=False)
    op.create_index('idx_incidents_reporter_id', 'incidents', ['reporter_id'], unique=False)
    op.create_index('idx_incidents_seat_id', 'incidents', ['seat_id'], unique=False)
    op.create_index('idx_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('incident_assignment_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('engineer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='assignment_request_status'), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_incident_assignment_requests_decided_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineer_profiles.id'], name=op.f('fk_incident_assignment_requests_engineer_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_assignment_requests_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_assignment_requests')),
    sa.UniqueConstraint('incident_id', 'engineer_id', name='uq_assignment_requests_incident_engineer')
    )
    op.create_index('idx_assignment_requests_engineer_id', 'incident_assignment_requests', ['engineer_id'], unique=False)
    op.create_index('idx_assignment_requests_incident_id', 'incident_assignment_requests', ['incident_id'], unique=False)
    op.create_index('idx_assignment_requests_status', 'incident_assignment_requests', ['status'], unique=False)
    op.create_table('incident_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_incident_notes_author_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_notes_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_notes'))
    )
    op.create_index('idx_incident_notes_incident_id', 'incident_notes', ['incident_id'], unique=False)
    op.create_table('incident_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'in_progress', 'blocked', 'resolved', 'closed', name='incident_status'), nullable=True),
    sa.Column('to_status', sa.Enum('open', 'in_progress', 'blocked', 'resolved', 'closed', name='incident_status'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_incident_status_history_changed_by'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_status_history_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_status_history'))
    )
    op.create_index('idx_incident_status_history_incident_id', 'incident_status_history', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_incident_status_history_incident_id', table_name='incident_status_history')
    op.drop_table('incident_status_history')
    op.drop_index('idx_incident_notes_incident_id', table_name='incident_notes')
    op.drop_table('incident_notes')
    op.drop_index('idx_assignment_requests_status', table_name='incident_assignment_requests')
    op.drop_index('idx_assignment_requests_incident_id', table_name='incident_assignment_requests')
    op.drop_index('idx_assignment_requests_engineer_id', table_name='incident_assignment_requests')
    op.drop_table('incident_assignment_requests')
    op.drop_index('idx_incidents_status', table_name='incidents')
    op.drop_index('idx_incidents_seat_id', table_name='incidents')
    op.drop_index('idx_incidents_reporter_id', table_name='incidents')
    op.drop_index('idx_incidents_priority', table_name='incidents')
    op.drop_index('idx_incidents_floor_id', table_name='incidents')
    op.drop_index('idx_incidents_category', table_name='incidents')
    op.drop_index('idx_incidents_building_id', table_name='incidents')
    op.drop_index('idx_incidents_assignee_id', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('idx_seats_floor_id', table_name='seats')
    op.drop_table('seats')
    op.drop_index('idx_floors_building_id', table_name='floors')
    op.drop_table('floors')
    op.drop_index('idx_engineer_profiles_availability', table_name='engineer_profiles')
    op.drop_table('engineer_profiles')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('buildings')
    # ### end Alembic commands ###

    # Hand-added: see the note at the top of this file. Dropping the tables
    # leaves the enum types orphaned, which breaks the next upgrade.
    for enum_name in ENUM_TYPE_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
