"""
SQLAlchemy models for the ACME facility incident schema (8 tables).

Part of: backend / data access.

Why its own file: the schema is the contract every service shares — incidents
join users and engineer profiles, facilities are read by three services — so
there is exactly one definition of it, and Alembic autogenerates migrations
from this metadata. Defining tables per service would let four copies of the
truth drift apart and make migrations ambiguous.

This file is the canonical copy. Do not edit the copies inside the service
directories — edit here, run ./sync.sh, and generate a migration.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Deterministic constraint names. Without this, PostgreSQL invents names for
# unique and check constraints, and an Alembic downgrade cannot drop what it
# cannot name.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}

# The email domain the brief restricts registration to. Enforced in the database
# as well as in the API: a CHECK constraint holds even if a future endpoint,
# script, or manual insert forgets the rule.
ACME_EMAIL_PATTERN = r"^[A-Za-z0-9._%+-]+@acme\.inc$"


class Base(DeclarativeBase):
    """Declarative base carrying the shared naming convention."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UserRole(str, enum.Enum):
    """Persona a user acts as. Drives every authorization check from Step 4 on."""

    EMPLOYEE = "employee"
    FACILITY_ADMIN = "facility_admin"
    ENGINEER = "engineer"


class AvailabilityStatus(str, enum.Enum):
    """Engineer's self-reported availability, used for workload dashboards."""

    AVAILABLE = "available"
    BUSY = "busy"
    OFF = "off"


class IncidentStatus(str, enum.Enum):
    """The five workflow states. Legal transitions are enforced in Step 5."""

    OPEN = "open"
    IN_PROGRESS = "in_progress"
    BLOCKED = "blocked"
    RESOLVED = "resolved"
    CLOSED = "closed"


class IncidentPriority(str, enum.Enum):
    """Priority set by a Facility Admin; employees may only request a change."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class AssignmentRequestStatus(str, enum.Enum):
    """Lifecycle of an engineer's request to take an unassigned incident."""

    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"


def pg_enum(enum_class: type[enum.Enum], name: str) -> Enum:
    """
    Build a native PostgreSQL enum column type.

    values_callable is essential: without it SQLAlchemy stores the Python member
    *names* (FACILITY_ADMIN) while the API, the seed data, and the approved SQL
    all use the lowercase *values* (facility_admin).
    """
    return Enum(
        enum_class,
        name=name,
        values_callable=lambda members: [member.value for member in members],
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    """
    UUID primary key generated by the database.

    Returns uuid.UUID objects, NOT strings. Every id crossing the API boundary
    must therefore be converted: str(model.id) on the way out, uuid.UUID(value)
    on the way in (a ValueError there is a 400, not a 500). Comparing an id to
    a raw string from a token or path parameter is silently False, which would
    make an ownership check fail open or closed by accident.

    gen_random_uuid() comes from the pgcrypto extension, which the first
    migration enables. Generating ids in the database keeps them correct no
    matter which service or script performs the insert.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at() -> Mapped[datetime]:
    """Creation timestamp, set by the database clock rather than the caller's."""
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


def updated_at() -> Mapped[datetime]:
    """
    Last-modified timestamp.

    onupdate covers ORM writes; server_default covers inserts from psql or the
    seed script, so neither path can leave the column null.
    """
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class User(Base):
    """A person who can sign in. One row per account, whatever the persona."""

    __tablename__ = "users"
    __table_args__ = (
        CheckConstraint(f"email ~* '{ACME_EMAIL_PATTERN}'", name="email_domain"),
        # The plain UNIQUE below is case-sensitive, so "Bob@ACME.inc" and
        # "bob@acme.inc" would be two accounts for one person — an account
        # takeover vector at login time. The API lowercases addresses on write
        # (Step 4); this functional index is what guarantees it even if some
        # future endpoint forgets to.
        Index("uq_users_email_lower", text("lower(email)"), unique=True),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    # Always a bcrypt hash (Step 4). Never a plaintext password, and never
    # included in an API response schema.
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    full_name: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[UserRole] = mapped_column(
        pg_enum(UserRole, "user_role"), nullable=False, server_default=UserRole.EMPLOYEE.value
    )
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    engineer_profile: Mapped["EngineerProfile | None"] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan", passive_deletes=True
    )


class EngineerProfile(Base):
    """
    Engineer-specific data hanging off a user account.

    A 1:1 extension rather than a separate identity, so an engineer signs in
    with the account a Facility Admin provisioned and every foreign key to a
    person still points at users.
    """

    __tablename__ = "engineer_profiles"
    __table_args__ = (Index("idx_engineer_profiles_availability", "availability"),)

    id: Mapped[uuid.UUID] = uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    specialty: Mapped[str | None] = mapped_column(Text)
    availability: Mapped[AvailabilityStatus] = mapped_column(
        pg_enum(AvailabilityStatus, "availability_status"),
        nullable=False,
        server_default=AvailabilityStatus.AVAILABLE.value,
    )
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    user: Mapped[User] = relationship(back_populates="engineer_profile")


class Building(Base):
    """Top of the facility hierarchy."""

    __tablename__ = "buildings"

    id: Mapped[uuid.UUID] = uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    address: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    # passive_deletes="all" stops SQLAlchemy from setting floors.building_id to
    # NULL when a building is deleted. Without it the ORM's nulling hits the NOT
    # NULL constraint first and the API answers 400, hiding the real reason —
    # the database's ON DELETE RESTRICT, which should surface as 409.
    floors: Mapped[list["Floor"]] = relationship(
        back_populates="building", passive_deletes="all"
    )


class Floor(Base):
    """
    A floor within a building.

    ON DELETE RESTRICT, not CASCADE: deleting a building that still has floors
    should fail with a 409 the admin can act on, not silently erase the
    locations that historical incidents point at.
    """

    __tablename__ = "floors"
    __table_args__ = (
        UniqueConstraint("building_id", "name", name="uq_floors_building_id_name"),
        Index("idx_floors_building_id", "building_id"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    building_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("buildings.id", ondelete="RESTRICT"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    building: Mapped[Building] = relationship(back_populates="floors")
    seats: Mapped[list["Seat"]] = relationship(back_populates="floor", passive_deletes="all")


class Seat(Base):
    """A seat on a floor. Labels are unique per floor, not globally."""

    __tablename__ = "seats"
    __table_args__ = (
        UniqueConstraint("floor_id", "label", name="uq_seats_floor_id_label"),
        Index("idx_seats_floor_id", "floor_id"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    floor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("floors.id", ondelete="RESTRICT"), nullable=False
    )
    label: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    floor: Mapped[Floor] = relationship(back_populates="seats")


class IncidentCategory(Base):
    """
    The list of things an incident can be about — one row per category.

    A table rather than a database enum, so a category can be added by
    inserting a row instead of shipping a migration:

        INSERT INTO incident_categories (slug, name, sort_order)
        VALUES ('grounds', 'Grounds and landscaping', 100);

    The trade-off, stated plainly: an enum makes an invalid value unstorable by
    the type system itself, whereas this relies on a foreign key. The foreign
    key is just as strict — the database still refuses an unknown category — but
    validation now happens against data rather than schema, so the API has to
    look the value up and return a clear 400 instead of Pydantic rejecting it
    before the handler runs.

    The slug is the primary key rather than a surrogate UUID. It is short,
    stable and already the value the API sends on the wire, so an incident row
    carries the category people actually read and nothing has to be joined to
    serialise one.
    """

    __tablename__ = "incident_categories"

    # A short machine name: lowercase, underscores, never shown to anybody.
    slug: Mapped[str] = mapped_column(Text, primary_key=True)
    # What a person sees in the dropdown, so adding a category does not require
    # a frontend change to give it a readable name.
    name: Mapped[str] = mapped_column(Text, nullable=False)
    # Controls dropdown order. Leaving gaps between the seeded values means a
    # new category can be slotted between two existing ones without renumbering.
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("100"))
    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()


class Incident(Base):
    """
    A reported facility or technology issue — the core record of the product.

    Location columns are independently nullable rather than a strict
    building > floor > seat chain, because a network issue may be reported
    against a seat alone and a lift fault against a building alone.
    """

    __tablename__ = "incidents"
    # eager_defaults makes SQLAlchemy fetch the database-generated reference in
    # the INSERT's RETURNING clause. Without it the attribute is expired after
    # the insert and the first read of incident.reference costs a second query.
    __mapper_args__ = {"eager_defaults": True}

    __table_args__ = (
        Index("uq_incidents_reference", "reference", unique=True),
        Index("idx_incidents_reporter_id", "reporter_id"),
        Index("idx_incidents_assignee_id", "assignee_id"),
        Index("idx_incidents_status", "status"),
        Index("idx_incidents_priority", "priority"),
        Index("idx_incidents_building_id", "building_id"),
        Index("idx_incidents_floor_id", "floor_id"),
        Index("idx_incidents_seat_id", "seat_id"),
        Index("idx_incidents_category", "category"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()

    # The number people actually use: "INC-0042" rather than a UUID nobody can
    # read out loud. Generated by the database from a sequence, not by the
    # application: two Lambdas inserting at the same moment would otherwise have
    # to agree on the next number, and nextval() is atomic so they do not.
    #
    # The UUID remains the identifier — every foreign key, URL and API call uses
    # it. This is a second, human-facing handle with its own unique constraint.
    reference: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=text(
            "'INC-' || lpad(nextval('incident_reference_seq')::text, 4, '0')"
        ),
    )

    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # A foreign key to incident_categories rather than an enum type, so the
    # list can be extended with an INSERT. RESTRICT, not CASCADE: removing a
    # category that incidents still reference must fail with a 409 rather than
    # silently deleting the incidents filed under it.
    category: Mapped[str] = mapped_column(
        Text,
        ForeignKey("incident_categories.slug", ondelete="RESTRICT"),
        nullable=False,
        server_default="other",
    )
    status: Mapped[IncidentStatus] = mapped_column(
        pg_enum(IncidentStatus, "incident_status"),
        nullable=False,
        server_default=IncidentStatus.OPEN.value,
    )
    priority: Mapped[IncidentPriority] = mapped_column(
        pg_enum(IncidentPriority, "incident_priority"),
        nullable=False,
        server_default=IncidentPriority.MEDIUM.value,
    )

    # SET NULL on the location keys: removing a seat must not delete the history
    # of what went wrong there.
    building_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("buildings.id", ondelete="SET NULL")
    )
    floor_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("floors.id", ondelete="SET NULL")
    )
    seat_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("seats.id", ondelete="SET NULL")
    )

    # Ownership and assignment are explicit columns so authorization is a query
    # filter ("reporter_id = me") rather than a check bolted on after fetching.
    reporter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    assignee_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("engineer_profiles.id", ondelete="SET NULL")
    )

    escalation_requested: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    escalated: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    escalation_reason: Mapped[str | None] = mapped_column(Text)
    blocked_reason: Mapped[str | None] = mapped_column(Text)

    # Lifecycle stamps that make the dashboard's timing metrics measurable
    # rather than estimated. Written by the Step 5 state machine.
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    assigned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_at: Mapped[datetime] = created_at()
    updated_at: Mapped[datetime] = updated_at()

    reporter: Mapped[User] = relationship(foreign_keys=[reporter_id])
    assignee: Mapped["EngineerProfile | None"] = relationship(foreign_keys=[assignee_id])
    # passive_deletes=True defers to the database's ON DELETE CASCADE: deleting
    # an incident with fifty notes is then one DELETE, not fifty-one.
    notes: Mapped[list["IncidentNote"]] = relationship(
        back_populates="incident", cascade="all, delete-orphan", passive_deletes=True
    )
    status_history: Mapped[list["IncidentStatusHistory"]] = relationship(
        back_populates="incident", cascade="all, delete-orphan", passive_deletes=True
    )


class IncidentNote(Base):
    """
    A message on an incident's thread.

    With no email or Slack integration in the MVP, this thread plus the status
    stepper is how an employee learns what is happening to their ticket.
    """

    __tablename__ = "incident_notes"
    __table_args__ = (Index("idx_incident_notes_incident_id", "incident_id"),)

    id: Mapped[uuid.UUID] = uuid_pk()
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False
    )
    # RESTRICT on the author: a note must always attribute to a real person, so
    # a user with notes cannot simply vanish.
    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    body: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = created_at()

    incident: Mapped[Incident] = relationship(back_populates="notes")


class IncidentStatusHistory(Base):
    """
    One row per status transition: who moved the incident, from what, when.

    This is what turns "average time to acknowledge/resolve" into a measured
    number instead of a guess, and it is append-only — rows are never updated.
    """

    __tablename__ = "incident_status_history"
    __table_args__ = (Index("idx_incident_status_history_incident_id", "incident_id"),)

    id: Mapped[uuid.UUID] = uuid_pk()
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False
    )
    # Null only for the row recording an incident's creation, which has no
    # previous status.
    from_status: Mapped[IncidentStatus | None] = mapped_column(
        pg_enum(IncidentStatus, "incident_status")
    )
    to_status: Mapped[IncidentStatus] = mapped_column(
        pg_enum(IncidentStatus, "incident_status"), nullable=False
    )
    changed_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    changed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    incident: Mapped[Incident] = relationship(back_populates="status_history")


class IncidentAssignmentRequest(Base):
    """
    An engineer asking to take an unassigned incident, pending admin approval.

    The unique constraint on (incident_id, engineer_id) is what makes a repeat
    request a 409 at the database level rather than a race between two
    concurrent Lambda invocations.
    """

    __tablename__ = "incident_assignment_requests"
    __table_args__ = (
        UniqueConstraint("incident_id", "engineer_id", name="uq_assignment_requests_incident_engineer"),
        Index("idx_assignment_requests_incident_id", "incident_id"),
        Index("idx_assignment_requests_engineer_id", "engineer_id"),
        Index("idx_assignment_requests_status", "status"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False
    )
    engineer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("engineer_profiles.id", ondelete="CASCADE"), nullable=False
    )
    status: Mapped[AssignmentRequestStatus] = mapped_column(
        pg_enum(AssignmentRequestStatus, "assignment_request_status"),
        nullable=False,
        server_default=AssignmentRequestStatus.PENDING.value,
    )
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    decided_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    decided_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
