"""
Alembic runtime environment.

Part of: backend / migrations.

Why its own file: Alembic needs to know two things — where the target schema
is defined and how to reach the database. Both answers live here so that
migrations use exactly the same connection rules as the running services
(db.database_url) and exactly the same schema definition the services import
(models.Base), making "the migration matches the code" true by construction.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from db import database_url
from models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Autogenerate compares the live database against this metadata.
target_metadata = Base.metadata

# Injected at runtime rather than read from alembic.ini, which holds no password.
config.set_main_option("sqlalchemy.url", database_url().replace("%", "%%"))


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting — used to review a migration first."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations against a live connection.

    compare_type and compare_server_default are on so that a changed column type
    or default shows up in an autogenerated migration instead of being silently
    skipped.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
